// <auto-generated />
using System;
using DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(AloperContext))]
    [Migration("20240505023842_UpdateAttribute2")]
    partial class UpdateAttribute2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BusinessObject.Contact", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("birthOfDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("contractEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateRange")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("depositAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("depositDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("idRoom")
                        .HasColumnType("int");

                    b.Property<string>("identification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("issuedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("numberOfPeople")
                        .HasColumnType("int");

                    b.Property<int>("numberOfVehicle")
                        .HasColumnType("int");

                    b.Property<string>("permanentAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("rentalStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("rentalTerm")
                        .HasColumnType("int");

                    b.Property<decimal>("retailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("signature")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("BusinessObject.ContactFurniture", b =>
                {
                    b.Property<string>("contactId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idFurniture")
                        .HasColumnType("int");

                    b.HasKey("contactId", "idFurniture");

                    b.HasIndex("idFurniture");

                    b.ToTable("ContactFurnitures");
                });

            modelBuilder.Entity("BusinessObject.ContactService", b =>
                {
                    b.Property<string>("contactId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("idService")
                        .HasColumnType("int");

                    b.HasKey("contactId", "idService");

                    b.HasIndex("idService");

                    b.ToTable("ContactServices");
                });

            modelBuilder.Entity("BusinessObject.Furniture", b =>
                {
                    b.Property<int>("idFurniture")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idFurniture"), 1L, 1);

                    b.Property<bool>("isActive")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idFurniture");

                    b.ToTable("Furnitures");
                });

            modelBuilder.Entity("BusinessObject.Service", b =>
                {
                    b.Property<int>("idService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idService"), 1L, 1);

                    b.Property<string>("dvt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("oldNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("priceService")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("idService");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("BusinessObject.ContactFurniture", b =>
                {
                    b.HasOne("BusinessObject.Contact", "Contact")
                        .WithMany("ContactFurnitures")
                        .HasForeignKey("contactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Furniture", "Furniture")
                        .WithMany("ContactFurnitures")
                        .HasForeignKey("idFurniture")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Furniture");
                });

            modelBuilder.Entity("BusinessObject.ContactService", b =>
                {
                    b.HasOne("BusinessObject.Contact", "Contact")
                        .WithMany("ContactServices")
                        .HasForeignKey("contactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Service", "Service")
                        .WithMany("ContactServices")
                        .HasForeignKey("idService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("BusinessObject.Contact", b =>
                {
                    b.Navigation("ContactFurnitures");

                    b.Navigation("ContactServices");
                });

            modelBuilder.Entity("BusinessObject.Furniture", b =>
                {
                    b.Navigation("ContactFurnitures");
                });

            modelBuilder.Entity("BusinessObject.Service", b =>
                {
                    b.Navigation("ContactServices");
                });
#pragma warning restore 612, 618
        }
    }
}
